%YAML:1.0
File.version: "1.0"
tags:
  -
    id: 0
    position: # x, y, z
      - -2.0
      - 0.0
      - 1.21
    orientation: # quaternion, w, x, y, z
      - -0.5
      - -0.5
      - 0.5
      - 0.5
  -
    id: 1
    position:
      - -2.00144
      - -1.99301
      - 0.81236
    orientation: # quaternion, w, x, y, z
      - -0.311201695048
      - -0.315981331
      - 0.62942999276
      - 0.63806565191